"""Rosetta Bear Firmware Tools - Generated by Autonomous Evolution Engine."""

from .rosetta_bear_rhz_coordination_bridge import RosettaBearRhzCoordinationBridge
from .rosetta_bear_rhz_meta_orchestrator import RosettaBearRhzMetaOrchestrator
from .rosetta_bear_rhz_self_building_firmware_forge import RosettaBearRhzSelfBuildingFirmwareForge
from .rosetta_bear_friction_detector import RosettaBearFrictionDetector
from .rosetta_bear_consensus_validator import RosettaBearConsensusValidator

ROSETTA_FIRMWARE_TOOLS = {
    "rosetta_bear_rhz_coordination_bridge": RosettaBearRhzCoordinationBridge,
    "rosetta_bear_rhz_meta_orchestrator": RosettaBearRhzMetaOrchestrator,
    "rosetta_bear_rhz_self_building_firmware_forge": RosettaBearRhzSelfBuildingFirmwareForge,
    "rosetta_bear_friction_detector": RosettaBearFrictionDetector,
    "rosetta_bear_consensus_validator": RosettaBearConsensusValidator,
}

__all__ = [
    "RosettaBearRhzCoordinationBridge",
    "RosettaBearRhzMetaOrchestrator",
    "RosettaBearRhzSelfBuildingFirmwareForge",
    "RosettaBearFrictionDetector",
    "RosettaBearConsensusValidator",
    "ROSETTA_FIRMWARE_TOOLS",
]
